### ISSUE TITLE
Missing GM2_red_200 color res value in SystemUI.

### ISSUE THREAD

**Issue by ReAllTh** [Project-Elixir/frameworks_base#2]
packages/SystemUI/res/values/colors.xml: line 40, 41 need GM2_red_200 color which is not defined.

**Comment by NavlysChen** [comment]
Sir, I have the same problem. Did you solve it?

**Comment by ReAllTh** [comment]
> Sir, I have the same problem. Did you solve it?

Using `<add-resource>` tag in `overlay/.../colors.xml` of ur device tree to add it
or just add it in the `packages/.../colors.xml`.(Not recommend, but since the former method didn`t worked for me, this is the exact way I could solve the problem.)

**Comment by NavlysChen** [comment]
> > Sir, I have the same problem. Did you solve it?
> 
> Using `<add-resource>` tag in `overlay/.../colors.xml` of ur device tree to add it or just add it in the `packages/.../colors.xml`.(Not recommend, but since the former method didn`t worked for me, this is the exact way I could solve the problem.)

I tried the latter, and it really worked, but I don't know if there is something wrong with the tree I used. After flashing the rom, it got stuck in the boot animation. Since I don't know how to adb the A12, I gave up.
